### ISSUE TITLE
fix: storybook default behavior is wrong

### ISSUE THREAD

**Issue by KazuhiroTamiwa** [ks-rogers/react-date-picks#1]
![year_month](https://user-images.githubusercontent.com/3402702/69001048-a7ab2680-091b-11ea-8b46-f62ffd040f3d.gif)

neither date-picker nor year-month-picker...

and, the label of the date-picker says year month, so let's fix it.

**Comment by shuhei-tagawa** [comment]
Thank for reporting.
Yes, that should be fixed.. we'll fix both parts you reported, thx.
