### ISSUE TITLE
SSRでリロードした際、一瞬CSSが当たっていない状態になりデザインが崩れる。

### ISSUE THREAD

**Issue by shuhei-tagawa** [ks-rogers/react-date-picks#7]
**バグ内容**
SSRでリロードした際、一瞬CSSが当たっていない状態になりデザインが崩れる。

![react-date-picks](https://user-images.githubusercontent.com/24493520/72686567-817f4e00-3b39-11ea-8c63-8a479838310c.gif)

**再現方法**
1. ローカルで `yalc` などを使って、SSRのプロジェクトにライブラリを読み込む。
2. リロードする。

**原因**
おそらくだが、ServerとClientでcss idが異なっていること。

```
index.js:1 Warning: Prop `className` did not match. Server: "sc-kpOJdX jxiWVG" Client: "sc-htpNat dwDKKo"
```

**影響**
デザインが一瞬崩れる。

**Comment by gyarasu** [comment]
ざっと調べただけですが共有です。

styled-componentsに起因するっぽい関連のissueをいくつか見つけました。

https://github.com/zeit/next.js/issues/7322
https://github.com/styled-components/styled-components/issues/1239#issuecomment-375991291

また、material-uiの既知のバグとして報告されていました。

**Comment by gyarasu** [comment]
ひとまず検証として、下記を使ってSSRしないようにしました。
https://github.com/kadirahq/react-no-ssr

表示崩れ自体は避けることができましたが、
表示されるまでに少し時間がかかります。

![picker-csr-only](https://user-images.githubusercontent.com/4948588/73754746-3a839080-47a8-11ea-94d5-f2153c227f6f.gif)

**Comment by gyarasu** [comment]
@shuhei-tagawa 
追加調査を行いました。もしかするとこれがドンピシャかもしれません。
https://styled-components.com/docs/tooling#serverside-rendering

（動作確認はまだです）

**Comment by gyarasu** [comment]
masterブランチにcheckoutしてローカルで試しました。

下記のようにすると、`Warning: Prop `className` did not match. Server: "Label__StyledLabel-iQRgab hPXccO" Client: "Label__StyledLabel-dxvnPe kioxOf"`がでなくなりました。

```.faterrc.js
export default {
  cjs: 'babel',
  esm: { type: 'babel', importLibToEs: true },
  preCommit: {
    eslint: true,
    prettier: true
  },
  extraBabelPlugins: [
    [
      'babel-plugin-import',
      {
        libraryName: 'babel-plugin-styled-components',
        libraryDirectory: 'es',
        style: true
      }
    ],
    ['styled-components', { ssr: true }]
  ]
}
```

**Comment by gyarasu** [comment]
上記で解決済みなのでクローズ
